### PR TITLE
logging via jul on JVM platform

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Comment by stuhood** [comment]
slf4j all the things.

**Comment by yschimke** [comment]
Fine by me, but this is the current set of dependencies

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

**Comment by kgoodier** [comment]
Looks simple and effective, for now. If this becomes a problem later, seems easy enough to replace with SLF4J. But until there is a strong need, I think keeping Whiskey as simple and dependency-free is important. To me, that is a key selling point. 

Another option would be for Whiskey to expose a "log this" delegate / callback, to which the app can subscribe and then feed to whatever logging system it wants, letting Whiskey punt the whole "java logging framework" problem. This is what CocoaSPDY does -- with the ability to automatically log when no delegate is attached and it's a debug build. I'm not sure this makes sense for the Java world, but there it is.

**Comment by stuhood** [comment]
> Another option would be for Whiskey to expose a "log this" delegate / callback, to which the app can subscribe and then feed to whatever logging system it wants

That's exactly what slf4j is.

**Comment by yschimke** [comment]
Stu, 

I agree with you on slf4j, I was sold on it years ago especially compared to commons-logging complexity and jul's abysmal API for callers and configuration.  We could depend on slf4j-api and let consumers decide the implementations.

3 reasons I haven't done that

1) I don't want to introduce the first dependency into whiskey.
2) twitter uses jul through finagle, so my code just works with jul.
3) slf4j has a bridge from jul that you can install if you want finagle, whiskey and other jul logging to go to your choice of backend.

I can certainly make this logging just the JVM default, and add a Platform.setLogger.  

But for me personally I think this request should just have this simple implementation.  And another change should look at how to do it properly on both platforms, JVM and Android.

**Comment by yschimke** [comment]
logging now joined

    DEB [20150831-10:21:51.941] whiskey: sent SYN_STREAM (374)
    DEB [20150831-10:21:51.941] whiskey: --> Stream-ID = 1
    DEB [20150831-10:21:51.941] whiskey: --> Priority = 4
    DEB [20150831-10:21:51.941] whiskey: --> Last = true
    DEB [20150831-10:21:51.941] whiskey:     :host: api.twitter.com
    DEB [20150831-10:21:51.941] whiskey:     :method: GET
    DEB [20150831-10:21:51.941] whiskey:     :scheme: https
    DEB [20150831-10:21:51.941] whiskey:     :version: HTTP/1.1
    DEB [20150831-10:21:51.941] whiskey:     :path: /robots.txt

**Comment by yschimke** [comment]
Stu, I raised https://github.com/twitter/whiskey/issues/18 which is a bigger task than this issue that just adds some critical missing logging.

**Comment by stuhood** [comment]
IIRC, if no `slf4j` impl is provided, it already defaults to a noop (and if not, there is an explicit noop implementation). So not adding oracle-specific deps to core is already accomplished there.

**Comment by yschimke** [comment]
I'm still not comfortable adding in a dependency on slf4j-api as part of this PR, so I'd suggest two possible paths

1) submit this as is and do additional work on the issue I raised.
2) remove the JUL logger and move it into my code.  Just allow overriding Platform.logger in this PR.

**Pull request merged**
